In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("heart_disease_dataset.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1000 non-null   int64
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64
 3   Blood Pressure           1000 non-null   int64
 4   Heart Rate               1000 non-null   int64
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           660 non-null    object
 7   Exercise Hours           1000 non-null   int64
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64
 12  Blood Sugar              1000 non-null   int64
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   object
 15  Heart Disease            1000 non-null   int64
dtypes: int64(8), object(8)
memory usage: 125.1+ KB

In [4]:
df.head()

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,Female,228,119,66,Current,Heavy,1,No,No,Yes,8,119,Yes,Atypical Angina,1
1,48,Male,204,165,62,Current,NaN,5,No,No,No,9,70,Yes,Typical Angina,0
2,53,Male,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196,Yes,Atypical Angina,1
3,69,Female,192,90,72,Current,NaN,4,No,Yes,No,7,107,Yes,Non-anginal Pain,0
4,62,Female,172,163,93,Never,NaN,6,No,Yes,No,2,183,Yes,Asymptomatic,0

In [5]:
df.isnull().sum()

Age                          0
Gender                       0
Cholesterol                  0
Blood Pressure               0
Heart Rate                   0
Smoking                      0
Alcohol Intake             340
Exercise Hours               0
Family History               0
Diabetes                     0
Obesity                      0
Stress Level                 0
Blood Sugar                  0
Exercise Induced Angina      0
Chest Pain Type              0
Heart Disease                0
dtype: int64

In [6]:
df["Alcohol Intake"].value_counts(dropna=False)

Alcohol Intake
Heavy       346
NaN         340
Moderate    314
Name: count, dtype: int64

In [7]:
df['Alcohol Intake'] = df['Alcohol Intake'].fillna("Unknown")

In [8]:
df["Heart Disease"].value_counts()

Heart Disease
0    608
1    392
Name: count, dtype: int64

In [9]:
df.isnull().sum()

Age                        0
Gender                     0
Cholesterol                0
Blood Pressure             0
Heart Rate                 0
Smoking                    0
Alcohol Intake             0
Exercise Hours             0
Family History             0
Diabetes                   0
Obesity                    0
Stress Level               0
Blood Sugar                0
Exercise Induced Angina    0
Chest Pain Type            0
Heart Disease              0
dtype: int64

In [10]:
#changing the datatype of categorical columns
from sklearn.preprocessing import LabelEncoder

In [11]:
le = LabelEncoder()

In [12]:
df.dtypes

Age                         int64
Gender                     object
Cholesterol                 int64
Blood Pressure              int64
Heart Rate                  int64
Smoking                    object
Alcohol Intake             object
Exercise Hours              int64
Family History             object
Diabetes                   object
Obesity                    object
Stress Level                int64
Blood Sugar                 int64
Exercise Induced Angina    object
Chest Pain Type            object
Heart Disease               int64
dtype: object

In [13]:
categorical_cols = [
    'Gender',
    'Smoking',
    'Alcohol Intake',
    'Family History',
    'Diabetes',
    'Obesity',
    'Exercise Induced Angina',
    'Chest Pain Type'
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [14]:
df.dtypes

Age                        int64
Gender                     int64
Cholesterol                int64
Blood Pressure             int64
Heart Rate                 int64
Smoking                    int64
Alcohol Intake             int64
Exercise Hours             int64
Family History             int64
Diabetes                   int64
Obesity                    int64
Stress Level               int64
Blood Sugar                int64
Exercise Induced Angina    int64
Chest Pain Type            int64
Heart Disease              int64
dtype: object

In [15]:
#creating the x an y features

X = df.drop('Heart Disease', axis=1)
y = df['Heart Disease']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
#training the random forest model
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators= 100, 
    random_state=42
)

In [19]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0])

In [22]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print('accuracy: ', accuracy)

accuracy:  1.0

In [23]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[118   0]
 [  0  82]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       118
           1       1.00      1.00      1.00        82

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

In [24]:
import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(feature_importance)

                    Feature  Importance
0                       Age    0.538316
2               Cholesterol    0.260509
12              Blood Sugar    0.035993
3            Blood Pressure    0.034182
4                Heart Rate    0.030410
7            Exercise Hours    0.021574
11             Stress Level    0.019843
5                   Smoking    0.011832
14          Chest Pain Type    0.011205
6            Alcohol Intake    0.008793
8            Family History    0.005995
10                  Obesity    0.005744
13  Exercise Induced Angina    0.005736
9                  Diabetes    0.005117
1                    Gender    0.004752

In [25]:
df.groupby("Heart Disease")[["Age", "Cholesterol"]].mean()

                     Age  Cholesterol
Heart Disease
0              44.128289   232.972039
1              64.956633   276.255102

In [26]:
df.groupby("Heart Disease")[["Age", "Cholesterol"]].min()

               Age  Cholesterol
Heart Disease
0               25          150
1               51          201

In [27]:
df.groupby("Heart Disease")[["Age", "Cholesterol"]].max()

               Age  Cholesterol
Heart Disease
0               79          349
1               79          349

In [28]:
import joblib

joblib.dump(model, "heart_model.pkl")

['heart_model.pkl']